# docker-compose file for local development and testing with container image.
version: '3.2'

services:
  # PostgreSQL database for Google Auth Webapp
  gauth-webapp-db:
    image: postgres
    env_file:
      - base.env
    volumes:
      - gauth-webapp-postgres-data-local:/var/lib/postgresql/data
      - gauth-webapp-postgres-backup-local:/backups

  # Debug SMTP provider
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  # Persistent volumes for postgres database data
  gauth-webapp-postgres-data-local:
  gauth-webapp-postgres-backup-local:
